version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
      time: "09:00"
      timezone: Etc/Greenwich
    commit-message:
      prefix: "deps"
      prefix-development: "deps"
      include: "scope"
    open-pull-requests-limit: 20
    groups:
      core-dependencies:
        patterns:
          - "@stylexjs/*"
          - "postcss"
      nextjs:
        patterns:
          - "next"
          - "@next/*"
          - "eslint-config-next"
      typescript-types:
        patterns:
          - "typescript"
          - "@types/*"
      build-tools:
        patterns:
          - "turbo"
          - "tsup"
          - "esbuild"
          - "webpack"
          - "rollup"
          - "vite"
          - "rspack"
          - "rsbuild"
      bundlers:
        patterns:
          - "webpack"
          - "rollup"
          - "esbuild"
          - "vite"
          - "rspack"
      code-quality:
        patterns:
          - "eslint*"
          - "prettier"
          - "lint-staged"
          - "shellcheck"
      git-tools:
        patterns:
          - "husky"
          - "@commitlint/*"
          - "commitizen"
          - "cz-conventional-changelog"
      version-management:
        patterns:
          - "@changesets/*"
          - "syncpack"
      dev-utilities:
        patterns:
          - "scripty"
          - "del-cli"
      test-dependencies:
        patterns:
          - "vitest"
          - "jest"
          - "@testing-library/*"
      e2e:
        patterns:
          - "playwright"
          - "@playwright/*"
      react-ecosystem:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
      babel-dependencies:
        patterns:
          - "@babel/*"
    versioning-strategy: auto
    labels:
      - "dependencies"
      - "typescript"
    # ignore:
    #   - dependency-name: "*"
    #     update-types: ["version-update:semver-major"]
    rebase-strategy: auto
    target-branch: "develop"
    reviewers:
      - "Dwlad90"
    assignees:
      - "Dwlad90"

  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: monthly
      time: "09:00"
      timezone: Etc/Greenwich
    commit-message:
      prefix: "cargo"
      include: "scope"
    open-pull-requests-limit: 20
    groups:
      swc-dependencies:
        patterns:
          - "swc_*"
      serialization:
        patterns:
          - "serde"
          - "serde_json"
      utilities:
        patterns:
          - "regex"
          - "indexmap"
          - "once_cell"
          - "colored"
          - "path-clean"
          - "lazy_static"
          - "murmur2"
          - "radix_fmt"
          - "phf"
          - "rustc-hash"
          - "node-resolve"
      parsers:
        patterns:
          - "cssparser"
      errors:
        patterns:
          - "anyhow"
          - "derive_more"
          - "color-backtrace"
      logging:
        patterns:
          - "log"
          - "pretty_env_logger"
          - "env_logger"
      testing:
        patterns:
          - "testing"
          - "insta"
          - "ctor"
    labels:
      - "dependencies"
      - "rust"
    # ignore:
    #   - dependency-name: "*"
    #     update-types: ["version-update:semver-major"]
    rebase-strategy: auto
    target-branch: "develop"
    reviewers:
      - "Dwlad90"
    assignees:
      - "Dwlad90"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
      time: "09:00"
      timezone: Etc/Greenwich
    commit-message:
      prefix: "ci"
      include: "scope"
    groups:
      actions:
        patterns:
          - "actions/*"
    labels:
      - "dependencies"
      - "github-actions"
    open-pull-requests-limit: 10
    target-branch: "develop"