changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: Breaking Changes 🛠
      labels:
        - 'BREAKING CHANGE'
    - title: Bug Fixes 🐛
      labels:
        - 'fix'
        - 'bug'
        - 'bugfix'
    - title: Features 🎉
      labels:
        - 'feature'
        - 'enhancement'
    - title: Performance Improvements 🚀
      labels:
        - 'performance'
        - 'speed'
    - title: Code Refactoring 🔨
      labels:
        - 'refactor'
        - 'clean'
    - title: Build System 🏗️
      labels:
        - 'build'
    - title: Continuous Integration 🤖
      labels:
        - 'ci'
        - 'pipeline'
        - 'workflows'
        - 'github-actions'
        - 'actions'
        - 'ci-cd'
        - 'CI'
        - 'CI/CD'
        - 'CI-CD'
    - title: Tests ✅
      labels:
        - 'test'
        - 'testing'
        - 'spec'
        - 'tests'
    - title: Documentation 📚
      labels:
        - 'docs'
        - 'documentation'
        - 'readme'
    - title: Styles 🎨
      labels:
        - 'style'
        - 'css'
        - 'design'
    - title: Reverts ⏪
      labels:
        - 'revert'
        - 'reverted'
    - title: Dependency Updates 📦
      labels:
        - 'dependencies'
        - 'dependency'
        - 'deps'
        - 'deps-update'
        - 'deps-updates'
        - 'deps-update'
        - 'deps-updates'
        - 'deps-update'
        - 'deps-updates'
    - title: Chores 🧹
      labels:
        - 'chore'
    - title: Other Changes 🔄
      labels:
        - '*'
