packages:
  - apps/*
  - crates/*
  - packages/*
autoInstallPeers: true
dedupePeerDependents: true
linkWorkspacePackages: deep
nodeVersion: 24.14.0
preferWorkspacePackages: true
resolvePeersFromWorkspaceRoot: true
saveWorkspaceProtocol: rolling
strictPeerDependencies: false
