[toolchain]
channel = "1.81.0"
components = ["rustfmt", "clippy"]
targets = [
  "wasm32-wasi",
  "x86_64-apple-darwin",
  "x86_64-pc-windows-msvc",
  "x86_64-unknown-linux-gnu",
  "x86_64-unknown-linux-musl",
  "aarch64-apple-darwin",
  "aarch64-unknown-linux-gnu",
]
profile = "minimal"
