use phf::phf_set;

// Using MDN data as a source of truth to populate the above sets
// by group in alphabetical order:

pub(crate) static UNITLESS_NUMBER_PROPERTIES: phf::Set<&'static str> = phf_set! {
  "WebkitLineClamp",
  "animationIterationCount",
  "aspectRatio",
  "borderImageOutset",
  "borderImageSlice",
  "borderImageWidth",
  "counterSet",
  "counterReset",
  "columnCount",
  "flex",
  "flexGrow",
  "flexShrink",
  "flexOrder",
  "gridRow",
  "gridRowStart",
  "gridRowEnd",
  "gridColumn",
  "gridColumnStart",
  "gridColumnEnd",
  "gridArea",
  "fontWeight",
  "hyphenateLimitChars",
  "lineClamp",
  "lineHeight",
  "maskBorderOutset",
  "maskBorderSlice",
  "maskBorderWidth",
  "opacity",
  "order",
  "orphans",
  "tabSize",
  "widows",
  "zIndex",
  "fillOpacity",
  "floodOpacity",
  "rotate",
  "scale",
  "shapeImageThreshold",
  "stopOpacity",
  "strokeDasharray",
  "strokeDashoffset",
  "strokeMiterlimit",
  "strokeOpacity",
  "strokeWidth",
  "mathDepth",
  "zoom",
};
