name: 'Git config'
description: 'Configure Git for GitHub Actions'
runs:
  using: 'composite'
  steps:
    - name: ⚙️ Configure Git
      shell: bash
      run: |
        git config --global user.name "${GITHUB_ACTOR}"
        git config --global user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"
