name: 'Turbo cache'
description: 'Cache Turbo build setup'
runs:
  using: 'composite'
  steps:
    - name: Cache turbo build setup
      uses: actions/cache@v4
      with:
        path: |
          .turbo
          **/.turbo
        key: ${{ runner.os }}-turbo-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-turbo-
