[package]
name = "test-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = { version = "2.5.0" }
serde = "1.0.202"
swc_core = { version = "0.92.5", features = [
  "common",
  "ecma_plugin_transform",
  "ecma_utils",
  "ecma_parser",
  "ecma_codegen",
  "ecma_codegen",
  "base_node",
] }

# TODO: remove this dependency after fixing dependencies of swc_core
swc_ecma_ast = { version = "0.113.2" }

clap = { version = "4.5.4", features = ["derive"] }

serde_json = "1.0.117"
