[package]
name = "test-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = { version = "2.5.0" }
serde = "1.0.201"
swc_core = { version = "0.92.2", features = [
  "common",
  "ecma_plugin_transform",
  "ecma_utils",
  "ecma_parser",
  "ecma_codegen",
  # "swc_ecma_parser",
  # "ecma_ast",

  # "allocator_node",
  "ecma_codegen",
  # "ecma_ast_serde",
  # "common_concurrent",
  # "bundler",
  # "ecma_loader",
  # "ecma_transforms",
  # "ecma_visit",
  # "css_codegen",
  # "css_visit",
  "base_node",
  # "css_parser",
  # "css_ast",
  # "base_concurrent",
] }

clap = {version = "4.5.4", features = ["derive"]}

serde_json = "1.0.117"
