[package]
name = "test-parser"
version = "0.1.0"
edition = "2021"
rust-version = "1.80.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = { version = "2.5.0" }
serde = "1.0.204"
swc_core = { version = "0.96.9", features = [
  "common",
  "ecma_plugin_transform",
  "ecma_utils",
  "ecma_parser",
  "ecma_codegen",
  "base_node"
] }

clap = { version = "4.5.11", features = ["derive"] }

serde_json = "1.0.120"
