[package]
name = "stylex_swc_plugin"
version = "0.2.0"
edition = "2021"
rust-version = "1.80.0"

[lib]
crate-type = ["cdylib", "rlib"]
doctest = false

[profile.release]
# This removes more dead code
codegen-units = 1
lto = true
# Optimize for size
# opt-level = "s"
# Optimize for performance, this is default so you don't need to specify it
opt-level = "z"

# Strip debug symbols
strip = "symbols"

[dependencies]
serde = "1.0.204"
swc_core = { version = "0.96.9", features = [
  "common",
  "ecma_plugin_transform",
  "ecma_utils",
  "ecma_parser",
  "ecma_codegen",
  "css_codegen",
  "css_visit",
  "css_parser",
  "css_ast",
] }

lazy_static = "1.5.0"
serde_json = "1.0.120"
regex = "1.10.5"
dashmap = "6.0.1"
indexmap = "2.2.6"
derive_more = { version = "0.99.18" }
convert_case = { version = "0.6.0" }
murmur2 = { version = "0.1.0" }
radix_fmt = { version = "1.0.0" }
phf = { version = "0.11.2", features = ["macros"] }
once_cell = { version = "1.19.0" }
colored = { version = "2.1.0" }
node-resolve = { version = "2.2.0" }
path-clean = { version = "1.0.1" }
cssparser = { version = "0.34.0" }
stylex_path_resolver = { path = "../path-resolver" }

[dev-dependencies]
swc_core = { version = "0.96.9", features = [
  "testing_transform",
  "ecma_parser",
] }
testing = "0.38.1"
insta = { version = "1.39.0", features = ["yaml"] }


# .cargo/config defines few alias to build plugin.
# cargo build-wasi generates wasm-wasi32 binary
# cargo build-wasm32 generates wasm32-unknown-unknown binary.

# wasm-pack build --target web --dev -d dist --out-name index
