import { Button } from './Button';
import { Meta, StoryObj } from '@storybook/react-vite';
declare const meta: Meta<typeof Button>;
export default meta;
type Story = StoryObj<typeof meta>;
export declare const Primary: Story;
export declare const Secondary: Story;
export declare const Danger: Story;
export declare const Small: Story;
export declare const Medium: Story;
export declare const Large: Story;
