import type { StyleXOptions, UseLayersType } from '@stylexswc/rs-compiler';
import type { Compiler, Configuration, LoaderContext } from '@rspack/core';
import type { RegisterStyleXRules } from '.';

export type CacheGroupOptions = NonNullable<
  Exclude<
    Exclude<Configuration['optimization'], undefined>['splitChunks'],
    undefined | false
  >['cacheGroups']
>[string];

type AsyncFnParams = Parameters<ReturnType<LoaderContext<unknown>['async']>>;

export type InputCode = AsyncFnParams['1'];
export type SourceMap = AsyncFnParams['2'];

export type CSSTransformer = (
  _css: string,
  _filePath: string | undefined
) => string | Buffer | Promise<string | Buffer>;

export interface StyleXPluginOption {
  /**
   * stylex options passed to stylex babel plugin
   *
   * @see https://stylexjs.com/docs/api/configuration/babel-plugin/
   */
  rsOptions?: Partial<StyleXOptions>;
  /**
   * Specify where stylex will be imported from
   *
   * @default ['stylex', '@stylexjs/stylex']
   */
  stylexImports?: StyleXOptions['importSources'];
  /**
   * Whether to use CSS layers
   *
   * @default false
   */
  useCSSLayers?: UseLayersType;
  /**
   * Next.js Mode
   *
   * @default false
   */
  nextjsMode?: boolean;

  /**
   * Enable other CSS transformation
   *
   * Since @stylexswc/rspack-plugin only injects CSS after all loaders, you can not use
   * postcss-loader. With this you can invoke `postcss()` here.
   */
  transformCss?: CSSTransformer;

  /**
   * Whether to extract CSS
   *
   * @default true
   */
  extractCSS?: boolean;

  /**
   * Loader execution order
   *
   * Determines when the StyleX transformation is applied relative to other rspack loaders.
   * Unlike the webpack plugin (which injects its loader per-module), the rspack plugin
   * registers a static module rule, so ordering maps to `Rule.enforce`:
   * - 'first': StyleX processes source code before normal loaders (`enforce: 'pre'`, recommended)
   * - 'last': StyleX processes after normal loaders have run (`enforce: 'post'`)
   *
   * @default 'first'
   */
  loaderOrder?: 'first' | 'last';
  /**
   * Customizes the cache group configuration for extracted CSS chunks.
   *
   * Allows you to override or extend the default rspack `splitChunks.cacheGroups` settings
   * for CSS generated by StyleX. This can be used to control how CSS is split into separate
   * files, optimize caching, or group styles according to your application's needs.
   *
   * @see https://rspack.rs/plugins/webpack/split-chunks-plugin#splitchunkscachegroups
   */
  cacheGroup?: CacheGroupOptions;

  /**
   * node_modules packages that must be processed by the stylex-loader.
   *
   * Rspack invokes JS loaders across a native boundary, so the plugin excludes
   * node_modules by default instead of matching everything like the webpack plugin.
   * List path fragments (e.g. '@stylexjs/', 'my-design-system') for packages that ship
   * untransformed StyleX source.
   *
   * @default ['@stylexjs/']
   */
  stylexPackages?: string[];
}

export type StyleXRspackLoaderOptions = {
  stylexImports: StyleXOptions['importSources'];
  rsOptions: Partial<StyleXOptions>;
  nextjsMode: boolean;
  extractCSS?: boolean;
};

export type SupplementedLoaderContext<Options = unknown> = LoaderContext<Options> & {
  StyleXRspackContextKey: {
    registerStyleXRules: RegisterStyleXRules;
  };
};

export type SWCPluginRule = {
  class_name: string;
  style: { ltr: string; rtl?: null | string };
  priority: number;
};

export type RspackCompiler = Compiler;
