[package]
name = "stylex_path_resolver"
version = "0.2.4"
edition = "2021"
rust-version = "1.80.0"
description = "Path resolver for StyleX SWC plugin"
license = "MIT"
repository = "https://github.com/Dwlad90/stylex-swc-plugin.git"


[lib]
crate-type = ["cdylib", "rlib"]
doctest = false

[dependencies]
serde.workspace = true
serde_json.workspace = true
swc_core = { workspace = true, features = ["common", "ecma_loader_node"] }
path-clean = { workspace = true }
regex.workspace = true
package-json = "0.4.0"
pathdiff = { version = "0.2.1" }
