import type { StyleXOptions, UseLayersType } from '@stylexswc/rs-compiler';
import type { LoaderContext } from 'webpack';
import type webpack from 'webpack';

export type CacheGroupOptions = NonNullable<
  Exclude<
    Exclude<webpack.Configuration['optimization'], undefined>['splitChunks'],
    undefined | false
  >['cacheGroups']
>[string];

type AsyncFnParams = Parameters<ReturnType<LoaderContext<unknown>['async']>>;

export type InputCode = AsyncFnParams['1'];
export type SourceMap = AsyncFnParams['2'];

export type CSSTransformer = (
  _css: string,
  _filePath: string | undefined
) => string | Buffer | Promise<string | Buffer>;

export interface StyleXPluginOption {
  /**
   * stylex options passed to the StyleX Rust compiler
   *
   * @see https://stylexjs.com/docs/api/configuration/babel-plugin/
   */
  rsOptions?: Partial<StyleXOptions>;
  /**
   * Specify where stylex will be imported from
   *
   * @default ['stylex', '@stylexjs/stylex']
   */
  stylexImports?: StyleXOptions['importSources'];
  /**
   * Whether to use CSS layers
   *
   * @default false
   */
  useCSSLayers?: UseLayersType;
  /**
   * Next.js Mode
   *
   * @default false
   */
  nextjsMode?: boolean;
  /**
   * Next.js App Router Mode
   *
   * Enables the cross-compiler rule registry so styles collected by the
   * server and edge-server compilers are merged into the client CSS asset.
   *
   * @default false
   */
  nextjsAppRouterMode?: boolean;

  /**
   * Enable other CSS transformation
   *
   * Since the StyleX plugin only injects CSS after all loaders, you can not
   * use postcss-loader. With this you can invoke `postcss()` here.
   */
  transformCss?: CSSTransformer;

  /**
   * Whether to extract CSS
   *
   * @default true
   */
  extractCSS?: boolean;

  /**
   * Loader execution order
   *
   * Determines when the StyleX transformation is applied relative to other loaders:
   * - 'first': StyleX processes source code before any other loaders (recommended)
   * - 'last': StyleX processes after all other loaders have run
   *
   * The webpack plugin injects its loader per-module; the rspack plugin
   * registers a static module rule, so ordering maps to `Rule.enforce`
   * ('first' -> 'pre', 'last' -> 'post').
   *
   * @default 'first'
   */
  loaderOrder?: 'first' | 'last';
  /**
   * Customizes the cache group configuration for extracted CSS chunks.
   *
   * Allows you to override or extend the default `splitChunks.cacheGroups`
   * settings for CSS generated by StyleX. This can be used to control how CSS
   * is split into separate files, optimize caching, or group styles according
   * to your application's needs.
   *
   * @see https://webpack.js.org/plugins/split-chunks-plugin/#splitchunkscachegroups
   */
  cacheGroup?: CacheGroupOptions;

  /**
   * node_modules packages that must be processed by the stylex-loader.
   *
   * By default, node_modules is excluded even if a module imports StyleX, so
   * only source that ships already-untransformed StyleX (e.g. component
   * libraries) needs to opt in here. List path fragments (e.g. '@stylexjs/',
   * 'my-design-system') for packages that ship untransformed StyleX source.
   *
   * @default ['@stylexjs/']
   */
  stylexPackages?: string[];

  /**
   * Path to a custom carrier stylesheet that receives the extracted StyleX
   * CSS — the file you import once at your app entrypoint. Absolute, or
   * relative to `compiler.context`.
   *
   * Replaces the default carrier shipped with the plugin
   * (`<plugin package>/stylex.css`): useful when a file named `stylex.css`
   * elsewhere in your project would collide with the default filename
   * pattern, or when you want the carrier to live in your own source tree.
   *
   * @example './src/styles/stylex-carrier.css'
   */
  carrierCss?: string;
}

export type StyleXLoaderOptions = {
  stylexImports: StyleXOptions['importSources'];
  rsOptions: Partial<StyleXOptions>;
  nextjsMode: boolean;
  nextjsAppRouterMode: boolean;
  extractCSS?: boolean;
};

export type SWCPluginRule = {
  class_name: string;
  style: { ltr: string; rtl?: null | string };
  priority: number;
};
