name: 'Turbo cache save'
description: 'Save Turbo build cache'
inputs:
  cache-key:
    description: 'Primary cache key returned by the turbo restore action'
    required: true
  cache-path:
    description: 'Cache path(s) for Turbo artifacts'
    required: false
    default: .turbo
runs:
  using: 'composite'
  steps:
    - name: Save turbo build cache
      uses: actions/cache/save@v5
      with:
        path: ${{ inputs['cache-path'] }}
        key: ${{ inputs['cache-key'] }}
