import fs from 'node:fs';
import path from 'node:path';

import { describe, expect, test } from 'vitest';

import { declarationKey, entryId } from '../lib/declaration.js';
import { harvestCorpus } from '../lib/harvest.js';
import type { DeclarationEntry } from '../lib/types.js';
import { temporaryDir } from './support.js';

/**
 * The harvester walks `<root>/crates/<crate>` for `.rs` files, so a case is a
 * throwaway tree holding one source. Scanning the real suites is what
 * `parity:harvest` does; these pin the extractors instead.
 */
function harvestOf(
  source: string,
  filename = 'tests/case.rs',
  crate = 'stylex-css'
): DeclarationEntry[] {
  const root = temporaryDir('parity-harvest-');
  const file = path.join(root, 'crates', crate, filename);
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, source, 'utf8');
  return harvestCorpus({ workspaceRoot: root });
}

/** Just the declarations, which is all a corpus entry means. */
function declarationsOf(source: string, filename?: string, crate?: string): [string, string][] {
  return harvestOf(source, filename, crate).map(entry => [entry.property, entry.value]);
}

describe('the scan surface', () => {
  // A list of crates loses a crate the day one is added. See `parity/README.md`.
  test('reads a crate nothing names', () => {
    expect(
      declarationsOf('let x = "*{color:red}";', 'src/tests/case.rs', 'a-brand-new-crate')
    ).toEqual([['color', 'red']]);
  });

  test('skips a source whose header says it is generated', () => {
    // `postcss-value-parser`'s `cases.rs` is generated *from* this corpus and
    // spells its inputs as CSS rules, so scanning it feeds the corpus its own
    // output back under a new origin.
    expect(
      declarationsOf('// @generated by a script -- do not edit by hand.\nlet x = "*{color:red}";')
    ).toEqual([]);
  });

  test('reads the marker as a header only, not as a value further down', () => {
    expect(declarationsOf('let x = "*{color:red}";\n// @generated\n')).toEqual([['color', 'red']]);
  });

  test('reads a doc-comment header too', () => {
    expect(declarationsOf('//! @generated\nlet x = "*{color:red}";')).toEqual([]);
  });
});

describe('shape 1 — direct normalize_css_property_value calls', () => {
  test('takes the property and value literals as a pair', () => {
    expect(
      declarationsOf(`
        #[test]
        fn t() {
          let result = normalize_css_property_value("color", "#ff0000", &opts);
        }
      `)
    ).toEqual([['color', '#ff0000']]);
  });

  test('takes raw-string values verbatim', () => {
    expect(
      declarationsOf(`
        #[test]
        fn t() {
          normalize_css_property_value("content", r#""a\\"b""#, &opts);
        }
      `)
    ).toEqual([['content', String.raw`"a\"b"`]]);
  });

  test('skips the definition of the function itself', () => {
    expect(declarationsOf('pub fn normalize_css_property_value(a: &str, b: &str) {}')).toEqual([]);
  });
});

describe('shape 2 — case tables looped through one property', () => {
  test('takes tuple inputs and ignores the expected outputs', () => {
    expect(
      declarationsOf(`
        #[test]
        fn t() {
          let cases = [
            ("calc-size(any, 300px)", "calc-size(any,300px)"),
            ("foo * bar", "foo * bar"),
          ];
          for (value, expected) in cases {
            assert_eq!(normalize_css_property_value("height", value, &opts), expected);
          }
        }
      `)
    ).toEqual([
      ['height', 'calc-size(any, 300px)'],
      ['height', 'foo * bar'],
    ]);
  });

  test('takes every element of a flat array of inputs', () => {
    expect(
      declarationsOf(`
        #[test]
        fn t() {
          let values = ["1px", "2px"];
          for value in values {
            normalize_css_property_value("width", value, &opts);
          }
        }
      `)
    ).toEqual([
      ['width', '1px'],
      ['width', '2px'],
    ]);
  });

  test('leaves a block alone when the call already passed a literal value', () => {
    // Shape 1 covers it; re-reading the block would attribute the expected
    // output to the property as though it were an input.
    expect(
      declarationsOf(`
        #[test]
        fn t() {
          assert_eq!(normalize_css_property_value("color", "red", &opts), "red");
        }
      `)
    ).toEqual([['color', 'red']]);
  });
});

describe('shapes 3 and 4 — whole rules in one literal', () => {
  test('reads the doubled-brace form the visitor tests use', () => {
    expect(declarationsOf('let x = "* {{ transitionProperty: opacity, margin-top; }}";')).toEqual([
      ['transitionProperty', 'opacity, margin-top'],
    ]);
  });

  test('reads the minified form', () => {
    expect(declarationsOf('let x = "*{color:red}";')).toEqual([['color', 'red']]);
  });

  test('reads a custom property name', () => {
    expect(declarationsOf('let x = "*{--myVar:blue}";')).toEqual([['--myVar', 'blue']]);
  });

  test('ignores a literal that is not a whole rule', () => {
    expect(declarationsOf('let message = "some prose";')).toEqual([]);
    expect(declarationsOf('let x = "1px#000";')).toEqual([]);
  });
});

describe('shape 5 — stylex.create objects in transform tests', () => {
  test('reads every declaration in the object', () => {
    expect(
      declarationsOf(`
        stylex_test!(t, |tr| x, r#"
          const styles = stylex.create({ x: { color: 'red', marginTop: '1px' } });
        "#);
      `)
    ).toEqual([
      ['color', 'red'],
      ['marginTop', '1px'],
    ]);
  });

  test('skips interpolated values, which are not literal CSS', () => {
    expect(
      declarationsOf(`
        stylex_test!(t, |tr| x, r#"
          const styles = stylex.create({ x: { width: '\${size}px', color: 'red' } });
        "#);
      `)
    ).toEqual([['color', 'red']]);
  });

  test('skips keys that are not CSS properties', () => {
    const harvested = declarationsOf(`
      stylex_test!(t, |tr| x, r#"
        const styles = stylex.create({ x: { default: 'a', ':hover': 'b', color: 'red' } });
      "#);
    `);
    expect(harvested).toEqual([['color', 'red']]);
  });

  test('ignores a raw string with no stylex.create in it', () => {
    expect(declarationsOf('let x = r#"const a = { color: \'red\' };"#;')).toEqual([]);
  });
});

describe('shape 5 — objects a stylex.env function is called with', () => {
  const fixture = (js: string): string => `
    stylex_test!(t, |tr| x, r#"
      const styles = stylex.create({
        ${js}
      });
    "#);
  `;

  test('skips the keys of the object handed to the call', () => {
    // `primary` and `secondary` name branches for the environment function to
    // choose between. Asking both compilers what `primary: red` means says
    // nothing about how a value is spelled.
    expect(
      declarationsOf(
        fixture(
          `root: { color: stylex.env.select({ primary: 'red', secondary: 'blue' }, 'primary') },`
        )
      )
    ).toEqual([]);
  });

  test('skips them where the call supplies the whole namespace', () => {
    expect(
      declarationsOf(fixture(`root: stylex.env.theme({ primary: 'red', size: 24 }, 'dark'),`))
    ).toEqual([]);
  });

  test('keeps a branch body, which sits one brace deeper than the selector', () => {
    expect(
      declarationsOf(
        fixture(`root: stylex.env.select({ compact: { padding: '4px' } }, 'compact'),`)
      )
    ).toEqual([['padding', '4px']]);
  });

  test('keeps the declarations around the call', () => {
    expect(
      declarationsOf(
        fixture(`root: { margin: '0', color: stylex.env.branch({ alternate: 'blue' }) },`)
      )
    ).toEqual([['margin', '0']]);
  });

  test('a brace inside a value does not shift what encloses the keys', () => {
    // The scan is over text. A value may spell a brace — `url("a{b")` is an
    // authored test value — and counting one as a block would put every key
    // after it under the wrong object.
    expect(
      declarationsOf(
        fixture(
          `root: { content: 'a{b', color: stylex.env.branch({ alternate: 'blue' }), marginTop: '1px' },`
        )
      )
    ).toEqual([
      ['content', 'a{b'],
      ['marginTop', '1px'],
    ]);
  });

  test('an escaped quote does not leave the scan inside a value', () => {
    // The value closes on the *second* quote. Reading the escaped one as the
    // end of the string would put the brace scan a level out for the rest of
    // the fixture, and `alternate` would harvest as a property.
    expect(
      declarationsOf(
        fixture(
          `root: { content: '\\'{', color: stylex.env.branch({ alternate: 'blue' }), marginTop: '1px' },`
        )
      )
    ).toEqual([
      ['content', "'{"],
      ['marginTop', '1px'],
    ]);
  });

  test('reads the callee however far the brace is from it', () => {
    // The `(` and the `{` are as far apart as a fixture can put them, and the
    // function name is long. Nothing about the distance decides the answer.
    expect(
      declarationsOf(
        fixture(`root: stylex.env.aVeryLongEnvironmentFunctionNameIndeed(
            {
              alternate: 'blue',
            }
          ),`)
      )
    ).toEqual([]);
  });

  test('skips them where a spread writes three dots in front of the call', () => {
    // `...stylex.env.colors({ color: 'yellow' })` is the shape the transform
    // suites use most, and the dots sit where a member chain would.
    expect(declarationsOf(fixture(`root: { ...stylex.env.colors({ color: 'yellow' }) },`))).toEqual(
      []
    );
  });

  test('a chain that merely ends in the receiver is a different receiver', () => {
    expect(
      declarationsOf(fixture(`root: options.stylex.env.select({ primary: 'red' }, 'primary'),`))
    ).toEqual([['primary', 'red']]);
  });

  test('a bare stylex.env read is not a call, so nothing is skipped for it', () => {
    expect(
      declarationsOf(fixture(`root: { color: stylex.env.brandPrimary, marginTop: '1px' },`))
    ).toEqual([['marginTop', '1px']]);
  });

  test('holds up under an env call nested in an env call', () => {
    expect(
      declarationsOf(
        fixture(
          `root: stylex.env.select({ a: stylex.env.select({ b: { color: 'red' } }, 'b') }, 'a'),`
        )
      )
    ).toEqual([['color', 'red']]);
  });

  test('reads 500 branches and 500 rules, and takes only the rules', () => {
    const branches = Array.from({ length: 500 }, (_, index) => `b${index}: '${index}px'`).join(
      ', '
    );
    const rules = Array.from(
      { length: 500 },
      (_, index) => `r${index}: { marginTop: '${index}px' }`
    ).join(', ');

    const harvested = declarationsOf(
      fixture(`root: stylex.env.select({ ${branches} }, 'b0'), ${rules}`)
    );

    expect(harvested).toHaveLength(500);
    expect(harvested.every(([property]) => property === 'marginTop')).toBe(true);
  });
});

describe('collection', () => {
  test('records the path and line each declaration came from', () => {
    const [entry] = harvestOf('\n\nlet x = "*{color:red}";', 'tests/where.rs');
    expect(entry?.origin).toBe('crates/stylex-css/tests/where.rs:3');
  });

  test('collapses duplicate declarations onto the first origin seen', () => {
    const harvested = harvestOf('let a = "*{color:red}";\nlet b = "*{color:red}";');
    expect(harvested).toHaveLength(1);
    expect(harvested[0]?.origin).toMatch(/:1$/);
  });

  test('keeps declarations that differ only in property or only in value', () => {
    expect(declarationsOf('let x = "*{color:red}"; let y = "*{color:blue}";')).toHaveLength(2);
    expect(declarationsOf('let x = "*{color:red}"; let y = "*{background:red}";')).toHaveLength(2);
  });

  test('skips generated snapshot directories', () => {
    expect(declarationsOf('let x = "*{color:red}";', '__swc_snapshots__/gen.rs')).toEqual([]);
  });
});

describe('shape 6 — verdict case tables', () => {
  test('takes the property and value, and never the expected output', () => {
    expect(
      declarationsOf(`
        #[test]
        fn t() {
          check(
            &[
              same("transitionDuration", "500ms", ".5s"),
              diverges("transform", "rotate(0rad)", "rotate(0rad)", "rotate(0deg)"),
            ],
            &default_options(),
          );
        }
      `)
    ).toEqual([
      ['transform', 'rotate(0rad)'],
      ['transitionDuration', '500ms'],
    ]);
  });

  test('reads the constructor whose expectation is the input itself', () => {
    expect(
      declarationsOf(`
        #[test]
        fn t() {
          check(&[unchanged("width", "var(--x)px")], &default_options());
        }
      `)
    ).toEqual([['width', 'var(--x)px']]);
  });

  test('skips the definitions of the constructors themselves', () => {
    expect(
      declarationsOf(`
        const fn unchanged(property: &'static str, value: &'static str) -> Case {}
        const fn same(property: &'static str, value: &'static str) -> Case {}
        const fn diverges(property: &'static str, value: &'static str) -> Case {}
      `)
    ).toEqual([]);
  });

  // A short name would otherwise match the tail of a longer identifier.
  test('does not match a call whose name merely ends in one of the constructors', () => {
    expect(
      declarationsOf(`
        #[test]
        fn t() {
          assert!(is_same("color", "red"));
        }
      `)
    ).toEqual([]);
  });
});

describe('shape 7 — rejection tables', () => {
  test('takes every value in the slice, against the property before it', () => {
    expect(
      declarationsOf(`
        #[test]
        fn t() {
          rejects(
            "width",
            &["*(", "/.5 /-1 *( *3"],
            UNCLOSED_FUNCTION,
            &default_options(),
          );
        }
      `)
    ).toEqual([
      ['width', '*('],
      ['width', '/.5 /-1 *( *3'],
    ]);
  });

  // The diagnostic is a message, not a CSS value. Harvesting it would put a
  // sentence in the corpus and report it as an acceptance divergence.
  test('stops at the end of the slice, so a later literal argument is not a value', () => {
    expect(
      declarationsOf(`
        #[test]
        fn t() {
          rejects("color", &[")("], "unclosed function", &default_options());
        }
      `)
    ).toEqual([['color', ')(']]);
  });

  test('skips the definition of the runner itself', () => {
    expect(
      declarationsOf(`
        fn rejects(property: &str, values: &[&str], expected: &str) {}
      `)
    ).toEqual([]);
  });
});

describe('what the source cannot fabricate', () => {
  test('a call spelled inside a value literal is not a call site', () => {
    // The JS fixture text in the transform suites is Rust string data, and it
    // can spell anything — including a call this harvester recognizes. Sites are
    // found on the masked source, so only real code counts.
    expect(
      declarationsOf(`
        #[test]
        fn a_value_that_mentions_the_harness() {
          let fixture = r#"
            content: unchanged("color", "fabricated")
          "#;
          unchanged("width", "1px");
        }
      `)
    ).toEqual([['width', '1px']]);
  });

  test('an identifier argument does not borrow a literal from further along', () => {
    // Shape 1 takes the first two literals after the parenthesis. When the
    // value argument is an identifier, the next literal is whatever follows —
    // here the *expected output*, which is the one thing the harness must never
    // harvest as an input, since deriving expectations from the reference
    // compiler is its whole purpose.
    const harvested = declarationsOf(`
      #[test]
      fn a_call_whose_value_is_a_variable() {
        assert_eq!(normalize_css_property_value("height", value, &opts), "expected-output");
      }
    `);

    expect(harvested).not.toContainEqual(['height', 'expected-output']);
  });
});

describe('identity', () => {
  test('an id follows the declaration, not its position', () => {
    expect(entryId('color', 'red')).toBe(entryId('color', 'red'));
    expect(entryId('color', 'red')).not.toBe(entryId('color', 'blue'));
    expect(entryId('color', 'red')).not.toBe(entryId('background', 'red'));
  });

  test('the key separator cannot be forged out of a property and a value', () => {
    // With a printable separator, `("a b", "c")` and `("a", "b c")` collide.
    expect(declarationKey('a b', 'c')).not.toBe(declarationKey('a', 'b c'));
  });
});
