name: Setup pnpm
description: Install pnpm package manager
runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4.4.0
      name: Install pnpm
      id: pnpm-install
      with:
        version: 10.30.3

    - uses: actions/setup-node@v6.3.0
      name: Install Node.js
      with:
        node-version: 24.14.0
        registry-url: 'https://registry.npmjs.org'
        cache: 'pnpm'

    - name: Install dependencies
      shell: bash
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          pnpm install --recursive --link-workspace-packages --no-frozen-lockfile
        else
          pnpm install --recursive --frozen-lockfile --link-workspace-packages
        fi
