name: Setup pnpm
description: Install pnpm package manager
runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4
      name: Install pnpm
      id: pnpm-install
      with:
        version: 9.9.0

    - uses: actions/setup-node@v4
      name: Install Node.js
      with:
        node-version: 20.17.0
        cache: 'pnpm'

    - name: Install dependencies
      shell: bash
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          pnpm install --recursive --link-workspace-packages --no-frozen-lockfile
        else
          pnpm install --recursive --frozen-lockfile --link-workspace-packages
        fi
