name: Clean up caches by branch
on:
  pull_request:
    types:
      - closed
  push:
    branches:
      - develop

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup
        shell: bash
        run: |
          if [ "${{ github.event_name }}" = "push" ]; then
            BRANCH_REF="refs/heads/develop"
            PR_REF="refs/pull/${{ github.event.pull_request.number }}/merge"

            echo "Cleaning develop branch caches (excluding benchmarks)..."
            cacheKeys=$(gh cache list --ref $BRANCH_REF --limit 100 --json key,id --jq '.[] | select(.key | contains("-benchmark") | not) | .id')
            for key in $cacheKeys; do
              gh cache delete $key
            done

            echo "Cleaning PR caches (excluding benchmarks)..."
            prCacheKeys=$(gh cache list --ref $PR_REF --limit 100 --json key,id --jq '.[] | select(.key | contains("-benchmark") | not) | .id')
            for key in $prCacheKeys; do
              gh cache delete $key
            done
          else
            BRANCH_REF="refs/pull/${{ github.event.pull_request.number }}/merge"
            echo "Cleaning PR caches (excluding benchmarks)..."
            cacheKeys=$(gh cache list --ref $BRANCH_REF --limit 100 --json key,id --jq '.[] | select(.key | contains("-benchmark") | not) | .id')
            for key in $cacheKeys; do
              gh cache delete $key
            done
          fi
          echo "Cache cleanup completed"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
