name: Clean up caches
on:
  workflow_call:
  workflow_dispatch:
    inputs:
      reference:
        description: 'Chache reference'
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.event.inputs.reference }}
  cancel-in-progress: true

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: 🧹 Cleanup
        shell: bash
        run: |
          REF="${{ github.event.inputs.reference }}"

          echo "Cleaning #${REF} caches..."

          ALL_CACHES=$(gh cache list --ref $REF --limit 100 --json key,id)

          NO_BENCHMARK=$(echo "${ALL_CACHES}" | jq '[.[] | select(.key | contains("-benchmark") | not)]')

          NO_TURBO=$(echo "${NO_BENCHMARK}" | jq '[.[] | select(.key | contains("-turbo") | not)]')

          NO_CODEQL=$(echo "${NO_TURBO}" | jq '[.[] | select(.key | contains("codeql-trap-") | not)]')

          NO_PNPM=$(echo "${NO_CODEQL}" | jq '[.[] | select(.key | contains("pnpm-") | not)]')

          FINAL_CACHES="${NO_PNPM}"

          echo "Filtered caches:"
          echo "${FINAL_CACHES}" | jq .

          echo "${FINAL_CACHES}" | jq -r '.[].id' | while read -r id; do
            echo "Deleting cache ${id}..."
            gh cache delete "$id" || true
          done

          echo "Cache cleanup completed"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}