name: Clean up caches by branch
on:
  pull_request:
    types:
      - closed

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: 🧹 Cleanup
        shell: bash
        run: |
          sleep 30

          PR_REF="refs/pull/${{ github.event.pull_request.number }}/merge"

          echo "Cleaning PR #${{ github.event.pull_request.number }} caches (excluding benchmarks)..."

          cacheKeys=$(gh cache list --ref $PR_REF --limit 100 --json key,id --jq '.[] | select(.key | endswith("-benchmark") | not) | .id')

          for key in $cacheKeys; do
            echo "Cache \"$key will\" will be deleted"
            gh cache delete $key
          done

          echo "Cache cleanup completed"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
