name: Clean up branch caches
on:
  push:
    branches:
      - develop
      - master
  delete:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: 🧹 Cleanup
        shell: bash
        run: |
          REF="${{ github.ref }}"

          run_id=$(gh workflow run .github/workflows/cleanup.yaml \
            --ref ${{ github.ref }} \
            --inputs reference=$REF \
            --repo ${{ github.repository }} \
            --json) || exit 1
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
