name: Clean up PR caches
on:
  pull_request:
    types:
      - closed
  pull_request_target:
    types:
      - closed

jobs:
  cleanup:
    runs-on: ubuntu-latest
    if: false
    steps:
      - name: 🧹 Cleanup
        shell: bash
        id: cleanup
        run: |
          REF="refs/pull/${{ github.event.pull_request.number }}/merge"

          run_id=$(gh workflow run cleanup.yaml \
            --ref ${{ github.ref }} \
            --field reference=$REF \
            --repo ${{ github.repository }}) || exit 1
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
