on:
  pull_request_target:
    types: [opened, synchronize, reopened, edited]

permissions:
  contents: read
  pull-requests: write

name: Conventional Release Labels
jobs:
  label:
    runs-on: ubuntu-latest
    if: github.event.action != 'closed'
    steps:
      - name: Execute assign labels
        id: action-assign-labels
        uses: mauroalderete/action-assign-labels@v1
        with:
          pull-request-number: ${{ github.event.pull_request.number }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          conventional-commits: |
            conventional-commits:
              - type: 'fix'
                nouns: ['FIX', 'Fix', 'fix', 'FIXED', 'Fixed', 'fixed']
                labels: ['bug']
              - type: 'feature'
                nouns: ['FEATURE', 'Feature', 'feature', 'FEAT', 'Feat', 'feat']
                labels: ['feat']
              - type: 'chore'
                nouns: ['CHORE', 'Chore', 'chore']
                labels: ['chore']
              - type: 'docs'
                nouns: ['DOCS', 'Docs', 'docs']
                labels: ['docs']
              - type: 'style'
                nouns: ['STYLE', 'Style', 'style']
                labels: ['style']
              - type: 'refactor'
                nouns: ['REFACTOR', 'Refactor', 'refactor']
                labels: ['refactor']
              - type: 'perf'
                nouns: ['PERF', 'Perf', 'perf']
                labels: ['perf']
              - type: 'test'
                nouns: ['TEST', 'Test', 'test']
                labels: ['test']
              - type: 'ci'
                nouns: ['CI', 'Ci', 'ci']
                labels: ['ci']
              - type: 'revert'
                nouns: ['REVERT', 'Revert', 'revert']
                labels: ['revert']
              - type: 'build'
                nouns: ['BUILD', 'Build', 'build']
                labels: ['build']
              - type: 'breaking_change'
                nouns: ['BREAKING CHANGE', 'BREAKING', 'MAJOR']
                labels: ['BREAKING CHANGE']

          maintain-labels-not-matched: false
          apply-changes: true