name: Conventional Release Labels

on:
  pull_request_target:
    types: [opened, synchronize, reopened, edited]

permissions:
  contents: read
  pull-requests: write

jobs:
  label:
    runs-on: ubuntu-latest
    if: github.event.action != 'closed'
    steps:
      - name: Execute assign labels
        id: action-assign-labels
        uses: mauroalderete/action-assign-labels@v1
        with:
          pull-request-number: ${{ github.event.pull_request.number }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          conventional-commits: |
            conventional-commits:
              - type: 'breaking_change'
                nouns: ['BREAKING CHANGE', 'BREAKING', 'MAJOR']
                labels: ['BREAKING CHANGE']
              - type: 'fix'
                nouns: ['FIX', 'Fix', 'fix', 'FIXED', 'Fixed', 'fixed', 'BUG', 'Bug', 'bug', 'BUGS', 'Bugs', 'bugs', 'BUGFIX', 'Bugfix', 'bugfix']
                labels: ['bug', 'fix']
              - type: 'feature'
                nouns: ['FEATURE', 'Feature', 'feature', 'FEAT', 'Feat', 'feat', 'FEATURES', 'Features', 'features']
                labels: ['feature']
              - type: 'perfomance'
                nouns: ['PERF', 'Perf', 'perf', 'perfomance', 'PERFORMANCE', 'Performance', 'performance']
                labels: ['performance']
              - type: 'refactor'
                nouns: ['REFACTOR', 'Refactor', 'refactor']
                labels: ['refactor']
              - type: 'build'
                nouns: ['BUILD', 'Build', 'build']
                labels: ['build']
              - type: 'CI'
                nouns: ['CI', 'Ci', 'ci', 'CI/CD', 'Ci/Cd', 'ci/cd', 'CI-CD', 'Ci-Cd', 'ci-cd', 'PIPELINE', 'Pipeline', 'pipeline', 'WORKFLOWS', 'Workflows', 'workflows', 'GITHUB ACTIONS', 'Github Actions', 'github actions', 'ACTIONS', 'Actions', 'actions']
                labels: ['CI']
              - type: 'test'
                nouns: ['TEST', 'Test', 'test']
                labels: ['test']
              - type: 'documentation'
                nouns: ['DOCS', 'Docs', 'docs', 'DOCUMENTATION', 'Documentation', 'documentation']
                labels: ['documentation']
              - type: 'style'
                nouns: ['STYLE', 'Style', 'style', 'CSS', 'Css', 'css', 'DESIGN', 'Design', 'design']
                labels: ['style']
              - type: 'revert'
                nouns: ['REVERT', 'Revert', 'revert', 'REVERTED', 'Reverted', 'reverted', 'Reapply', 'REAPPLY', 'Reapply', 'reapply', 'REVERTING', 'Reverting', 'reverting']
                labels: ['revert']
              - type: 'dependencies'
                nouns: ['DEPS', 'Deps', 'deps', 'DEPENDENCIES', 'Dependencies', 'dependencies', 'DEPS-UPDATE', 'Deps-Update', 'deps-update', 'DEPS-UPDATES', 'Deps-Updates', 'deps-updates', 'DEPS-UPDATE', 'Deps-Update', 'deps-update', 'dev-deps', 'DEV-DEPS', 'Dev-Deps', 'dev-deps', 'DEV-DEPENDENCIES', 'Dev-Dependencies', 'dev-dependencies', 'DEV-DEPS-UPDATE', 'Dev-Deps-Update', 'dev-deps-update', 'DEV-DEPS-UPDATES', 'Dev-Deps-Updates', 'dev-deps-updates', 'DEV-DEPS-UPDATE', 'Dev-Deps-Update', 'dev-deps-update']
                labels: ['dependencies']
              - type: 'chore'
                nouns: ['CHORE', 'Chore', 'chore', 'CHORES', 'Chores', 'chores']
                labels: ['chore']

          maintain-labels-not-matched: false
          apply-changes: true
