on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

name: Conventional Release Labels
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: bcoe/conventional-release-labels@v1
        with:
          type_labels: '["feat", "fix", "chore", "docs", "style", "refactor", "perf", "test", "build", "ci", "revert"]'