name: PR Merge

on:
  issue_comment:
    types: [created]

jobs:
  merge:
    name: Fast Forward PR Merge
    if: |
      github.event.issue.pull_request != '' &&
      contains(github.event.comment.body, '/merge') &&
      contains(fromJson('["dwlad90"]'), github.event.comment.user.login)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code into workspace directory
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Merge
        id: ff-only
        uses: endre-spotlab/fast-forward-js-action@2.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          success_message: 'Success! Fast forwarded ***target_base*** to ***source_head***! ```git checkout target_base && git merge source_head --ff-only``` '
          failure_message: 'Failed! Cannot do fast forward!'
          production_branch: 'master'
          staging_branch: 'develop'
          update_status: true
