name: PR Merge

on:
  issue_comment:
    types: [created]

jobs:
  merge:
    name: Fast Forward PR Merge
    permissions:
      contents: write
      statuses: write
      pull-requests: write
      actions: write

    if: |
      github.event.issue.pull_request != '' &&
      contains(github.event.comment.body, '/merge') &&
      contains(fromJson('["dwlad90"]'), github.event.comment.user.login)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code into workspace directory
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Merge
        id: ff-only
        uses: endre-spotlab/fast-forward-js-action@2.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          success_message: 'Success! Fast forwarded ***target_base*** to ***source_head***!'
          failure_message: 'Failed! Cannot do fast forward!'
          production_branch: 'master'
          staging_branch: 'develop'
          update_status: true
      - name: 🧹 Cleanup
        shell: bash
        id: cleanup
        if: false
        run: |
          REF="${{ github.ref }}"

          run_id=$(gh workflow run cleanup.yaml \
            --ref $REF \
            --field reference=$REF \
            --repo ${{ github.repository }}) || exit 1
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
