name: Pre-release

on:
  push:
    tags:
      - "*.*.*"
      - "*.*.*-*.*"
jobs:
  generate-pre-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set prerelease variable
        id: prerelease
        run: |
          if [[ "${GITHUB_REF#refs/tags/}" == *-* ]]; then
            echo "::set-output name=prerelease::true"
          else
            echo "::set-output name=prerelease::false"
          fi
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: ${{ steps.prerelease.outputs.prerelease }}
          generate_release_notes: true
          draft: true
          fail_on_unmatched_files: true