name: "Mark stale issues and pull requests"
on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: "This issue has been marked as stale due to 30 days of inactivity. If this issue is still relevant, please comment to keep it open."
          stale-pr-message: "This pull request has been marked as stale due to 30 days of inactivity. If this PR is still relevant, please comment to keep it open."
          days-before-stale: 30
          days-before-close: 7
          exempt-issue-labels: "pinned,security"
          exempt-pr-labels: "pinned,security"
          stale-issue-label: "stale"
          stale-pr-label: "stale"
