name: Validate StyleX SWC plugin

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
      - converted_to_draft

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  lint:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup

      - name: Lint code
        run: pnpm run -r lint:check

  format:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup

      - name: Format code
        run: pnpm run -r format:check

  test:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup

      - name: Run tests
        run: pnpm run -r --filter='!@stylexswc/rs-compiler' test
        env:
          RUST_MIN_STACK: 16777216

  build:
    runs-on: ubuntu-latest
    needs: [test, lint, format]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup

      - name: Build project
        run: pnpm run --filter @stylexswc/swc-plugin build

      - name: Check build artifacts
        run: pnpm run --filter @stylexswc/swc-plugin check:artifacts
