name: Dispatch Workflow

on:
  workflow_dispatch:
    inputs:
      type:
        description: 'Release tag'
        required: true
        type: choice
        options:
          # - 'major'
          - 'minor'
          - 'patch'
      prerelease:
        description: 'Is this a prerelease?'
        type: boolean
        default: false
      prerelease-tag:
        description: 'Prerelease tag'
        required: false
        type: string
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Find previous release
        id: find
        run: |
          if [ "${{ github.event.inputs.prerelease }}" = "true" ]; then
            regex='^[0-9]+\.[0-9]+\.[0-9]+(-[0-9]+\.[0-9]+)?$'
          else
            regex='^[0-9]+\.[0-9]+\.[0-9]+$'
          fi
          previousTag=$(git tag --list | grep -E "$regex" | sort -V | tail -n 1)
          echo "::set-output name=previousTag::$previousTag"

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.find.outputs.previousTag }}
          release_name: Release ${{ steps.find.outputs.previousTag }}
          draft: false
          prerelease: ${{ github.event.inputs.prerelease }}
